#version: "3"
#
#services:
#  mysql:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD
#    volumes:
#      - mysql:/var/lib/mysql
#    ports:
#      - "33060:3306"
#
#volumes:
#  mysql:
